name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase and related dependencies
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.0.0
  firebase_core: ^2.32.0
  change_app_package_name: ^1.0.0

  # Other dependencies
  image_picker: ^0.8.7
  fl_chart: ^0.36.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/1024.png"

flutter:
  uses-material-design: true

  # Correct indentation for the assets section
  assets:
    - assets/clothes/
    - assets/hoodies/
    - assets/jeans/
    - assets/shoes/
    - assets/t-shop.jpeg
    - assets/hoodie-shop.jpeg
    - assets/jean-shop.jpeg
    - assets/shoe-shop.jpeg 
      

