// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9N7RKjm5VlPrKpzGweH8-1OaU_1CrZhU',
    appId: '1:1003974995773:web:1e56ea57d8f64a83d89f54',
    messagingSenderId: '1003974995773',
    projectId: 'redcollar-92563',
    authDomain: 'redcollar-92563.firebaseapp.com',
    storageBucket: 'redcollar-92563.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3SgTMShfClIKskAE4dUlaSQ9zDzTpOM',
    appId: '1:1003974995773:android:6fbb0749961c9b6ad89f54',
    messagingSenderId: '1003974995773',
    projectId: 'redcollar-92563',
    storageBucket: 'redcollar-92563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2osZkxvvw07D6KvQg3U9zuklTS1IKzWg',
    appId: '1:1003974995773:ios:8bf208ccc7d659bdd89f54',
    messagingSenderId: '1003974995773',
    projectId: 'redcollar-92563',
    storageBucket: 'redcollar-92563.firebasestorage.app',
    androidClientId: '1003974995773-cuvded4gne5l1h79krfvtom4fgti91gs.apps.googleusercontent.com',
    iosClientId: '1003974995773-1iccemj78tv5ec0moonroujdcilkdvis.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2osZkxvvw07D6KvQg3U9zuklTS1IKzWg',
    appId: '1:1003974995773:ios:8bf208ccc7d659bdd89f54',
    messagingSenderId: '1003974995773',
    projectId: 'redcollar-92563',
    storageBucket: 'redcollar-92563.firebasestorage.app',
    androidClientId: '1003974995773-cuvded4gne5l1h79krfvtom4fgti91gs.apps.googleusercontent.com',
    iosClientId: '1003974995773-1iccemj78tv5ec0moonroujdcilkdvis.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9N7RKjm5VlPrKpzGweH8-1OaU_1CrZhU',
    appId: '1:1003974995773:web:55cd70588992a7d7d89f54',
    messagingSenderId: '1003974995773',
    projectId: 'redcollar-92563',
    authDomain: 'redcollar-92563.firebaseapp.com',
    storageBucket: 'redcollar-92563.firebasestorage.app',
  );
}
